#ifndef DEFS_H_
#define DEFS_H_

//#define DEBUG 1

#define MAPS_DIRECTORY "CalProj1Maps/"
#define NODES_DEFAULT_FILENAME "nodes.txt"
#define ROADS_DEFAULT_FILENAME "roads.txt"
#define SUBROADS_DEFAULT_FILENAME "subroads.txt"


#define GRAPH_VIEWER_WINDOW_WIDTH (1024 - 5)
#define GRAPH_VIEWER_WINDOW_HEIGTH (768 - 40)
#define GRAPH_VIEWER_WIDTH GRAPH_VIEWER_WINDOW_WIDTH
#define GRAPH_VIEWER_HEIGTH GRAPH_VIEWER_WINDOW_HEIGTH
#define GRAPH_VIEWER_AUTO_ARRANJE_NODES_POSITION_ON_GRAPH false


#define NODE_DEFAULT_COLOR "white"
#define NODE_PATH_COLOR "yellow"
#define NODE_START_PATH_COLOR "cyan"
#define NODE_END_PATH_COLOR "blue"
#define NODE_VISITED_COLOR "darkGray"

//#define USE_COORDINATES_INSTEAD_PROJECTIONS 1
#define NODES_COORDENATES_OFFSET pow(10, 5)
#define NODES_PROJECTION_OFFSET pow(10, 7)
#define NODE_LONGITUDE_PROJECTION_TRANSFORMATION_OFFSET (GRAPH_VIEWER_WIDTH * 0.1)
#define NODE_LATITUDE_PROJECTION_TRANSFORMATION_OFFSET (GRAPH_VIEWER_HEIGTH * 0.1)

#define SUBROAD_TIME_TO_TRAVEL_OFFSET_PER_CONNECTED_SUBROAD 2
#define SUBROAD_THICKNESS_MAXIMUM 10

#define ANIMATION_SLEEP 1000



#endif /* DEFS_H_ */
